#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
/home/diablo/.config/polybar/launch.sh --forest
picom -b
feh --randomize --bg-fill ~/.config/bspwm/wallpapers/ &



## Configuraciones -------------------------------#
bspc monitor -d  1 2 3 4 5

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config focused_border_color "$BLUE" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer truee

## Reglas para ventanas -------------------------------#

# remove all rules first
bspc rule -r *:*

# 1 > terminal
bspc rule -a URxvt desktop='^1' floating=onfollow=on focus=on

# 2 > web
bspc rule -a Firefox desktop='^2' follow=on focus=on

# 3 > file
bspc rule -a nautilus desktop='^3' follow=on focus=on

# 5 > file
bspc rule -a Gedit desktop='^5' follow=on focus=on


# Reglas especiales
bspc rule -a URxvt state=floating sticky=on center=true
